-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtIIyUKZKjYHz0JTw
LJyS2OLBGFSOqbBdZdNj5458kDSgCgYIKoZIzj0DAQehRANCAAQq4K7icRV77lmw
tNji9YbTpQXcPkL/EMqEBgTle2RnScQ8WoGtvhlSFvot7k2Cvz/TM0QkfF36St6s
KuusXhpW
-----END PRIVATE KEY-----